/**
 * 100 short filmmaking facts for the wait card — shooting methods, camera
 * history, and documented on-set lore. Deliberately below-the-surface: no
 * "did you know Titanic was expensive" filler. Where a story is industry
 * legend rather than verified record, it's framed as such.
 */

export const FILM_FACTS: string[] = [
  'Kubrick shot Barry Lyndon\'s candlelit scenes on f/0.7 Zeiss lenses built for NASA satellite photography — depth of field so shallow that actors leaning back an inch went soft.',
  'The dolly zoom was invented for Vertigo: track backwards while zooming in, and the subject stays the same size as the world stretches behind them.',
  'Deakins lit the night exteriors of 1917 so the flare-lit ruins would work from any camera direction — the whole sequence was blocked to real burn-times of parachute flares.',
  'The Shining\'s Steadicam work was operated by its inventor, Garrett Brown, often inches off the floor — a height he called "the child\'s point of view".',
  'Jaws\' mechanical shark failed so often in salt water that Spielberg shot around it — the yellow barrels became the shark, and the film got scarier for it.',
  'The Copacabana oner in Goodfellas exists because Scorsese couldn\'t get permission to use the front entrance — the kitchen route was a workaround that became the point.',
  'For Children of Men\'s car ambush oner, a rig called the Doggicam let the camera fly around inside the car while the roof was removed and the actors kept driving.',
  'Emmanuel Lubezki shot The Revenant almost entirely in natural light — the crew had roughly 90 minutes of usable "soft" light a day and rehearsed everything to hit it.',
  'Days of Heaven was largely shot at magic hour — about 25 usable minutes a day. Almendros and Malick simply waited, for an entire harvest season.',
  'Hitchcock\'s Rope hides its cuts by dollying into backs and furniture — a film reel only held about 10 minutes, so the "single take" was a physical impossibility he faked.',
  'Russian Ark (2002) genuinely is one take: 96 minutes, 2,000 actors, three orchestras, one Steadicam pass through the Hermitage — after three false starts, on the fourth attempt.',
  'The Matrix\'s bullet time used 120 still cameras firing in sequence around the actor, interpolated into motion — a Victorian chronophotography idea revived with CGI stitching.',
  'Inception\'s corridor fight was shot in a 100-foot rotating set — Joseph Gordon-Levitt trained for weeks and the crew bolted the camera to the drum so gravity itself appears to shift.',
  'Early Technicolor cameras ran three separate strips of film through a beam-splitting prism — they were so big and loud they lived inside soundproofed "blimps" the size of refrigerators.',
  'The Wilhelm scream — Hollywood\'s recycled stock scream — has appeared in over 400 films; sound designer Ben Burtt named it after a minor character shot in a 1953 western.',
  'Foley is named after Jack Foley, who performed live sound effects for early Universal talkies in a single pass — footsteps, cloth, props — a craft still done the same way today.',
  '"MOS" on a slate means shooting without sound. The beloved origin story — a German director saying "mit out sound" — is unverified, but the industry keeps telling it anyway.',
  'The "martini shot" is the last setup of the day; the second-to-last is the "Abby Singer", named after an AD famous for calling it to buy the crew packing time.',
  'Orson Welles put ceilings on Citizen Kane\'s sets — almost unheard of in 1941 — so Gregg Toland could shoot from the floor with wide lenses and deep focus.',
  'Gordon Willis underexposed The Godfather so aggressively that Paramount executives thought the dailies were ruined. His nickname afterwards: The Prince of Darkness.',
  'The cat in Don Corleone\'s lap was a stray Coppola found on the Paramount lot that morning. Its purring was so loud some of Brando\'s lines had to be looped.',
  'Silent films were hand-cranked at roughly 16–18 frames per second; 24fps only became standard because optical sound needed a constant film speed to stay in pitch.',
  'Kurosawa had the rain in Seven Samurai\'s final battle dyed with black ink so it would read on black-and-white film stock.',
  'For Ran, Kurosawa built a real castle on the slopes of Mount Fuji and burned it down in one take — no second castle existed.',
  'Herzog actually hauled a 320-ton steamship over a hill for Fitzcarraldo, refusing miniatures: "the audience would know." It took months and destroyed two ships.',
  'Tarkovsky shot most of Stalker twice — a lab accident (or sabotage, accounts differ) destroyed a year of footage, so he simply started again with a new cinematographer.',
  'The Lord of the Rings used "forced perspective" rigs that physically slid actors and set pieces during camera moves, keeping hobbits small even in moving shots.',
  'The chariot race in Ben-Hur (1959) took five weeks and covered 18 acres — the arena was the largest set yet built, and stunt riders trained for months with real teams.',
  'Lawrence of Arabia\'s mirage entrance was shot on a 482mm lens Panavision built specially — reportedly used for that shot and little else since.',
  'Barry Lyndon\'s zooms were done on a specially adapted 20:1 zoom lens; Kubrick used slow zoom-outs to end scenes like paintings receding into frames.',
  'The odd, dreamlike look of the Wizard of Oz horses "of a different color" came from sponging them with flavored gelatin powder — the horses kept licking it off between takes.',
  'Psycho\'s shower blood was Bosco chocolate syrup — it read better than stage blood in black and white, and the sound of stabbing was a knife in a casaba melon.',
  'Raiders\' swordsman-vs-gun gag exists because Harrison Ford had dysentery and couldn\'t shoot the planned whip fight. He suggested just shooting him. One take.',
  'The T. rex animatronic in Jurassic Park absorbed rain during the breakout scene and shuddered from the water weight — crews blow-dried its skin between takes.',
  'The Star Wars fleet was "kitbashed" from hundreds of commercial model kits — tank parts and battleship guns glued onto ship hulls to create believable surface detail.',
  '"I know" — Han Solo\'s reply to "I love you" — came out of a rehearsal between Irvin Kershner and Harrison Ford; the scripted line was "I love you too."',
  'The Empire Strikes Back\'s asteroid field includes a potato and a shoe among the miniatures — ILM modelers slipping objects past deadline fatigue and, legend says, a bet.',
  'For 2001, Kubrick built a 38-foot rotating centrifuge so Ferris-wheel jogging could be shot in camera — the operator was strapped in as the drum turned around him.',
  'The Alien chestburster scene was described to the cast only vaguely — the actors knew what would happen, but the blood hitting Veronica Cartwright was not rehearsed. Her horror is real.',
  'Ridley Scott used his own children in spacesuits for wide shots of the Alien landing party to make the Nostromo\'s sets look bigger.',
  'Blade Runner\'s spinner cars had to be filmed wet-down at night partly to hide that the "futuristic city" was a redressed 1929 backlot street.',
  'The French Connection\'s chase was partly shot without permits at real speed through Brooklyn — a real collision with a civilian car was left in the film.',
  'Bullitt\'s Mustang chase invented the modern car-chase grammar partly through mistake: the hubcap-losing jump takes happen out of sequence, and nobody cared.',
  'For Mad Max: Fury Road, George Miller\'s editor (his wife, Margaret Sixel) cut 480 hours of footage; her rule was to centre the action in frame so eyes never have to hunt during fast cuts.',
  'Fury Road\'s stunts used the "Edge Arm" — a crane-mounted, gyro-stabilised camera arm on a moving vehicle — so the camera could swing through explosions between real trucks.',
  'Titanic\'s ocean was a 17-million-gallon tank in Baja with a 90%-scale ship that could be tilted and partially sunk on hydraulics.',
  'Gravity was largely shot inside a "light box" — an LED cage projecting the rotating Earth onto Sandra Bullock\'s face, so light moved instead of the camera.',
  'Interstellar\'s corn was real: Nolan planted 500 acres, shot the film, then sold the harvest — reportedly close to breaking even on the field.',
  'Nolan\'s Dunkirk mounted IMAX cameras on real Spitfires; an IMAX camera is so loud dialogue near one is essentially unrecordable.',
  'Only a few dozen IMAX film cameras exist in the world; when one sank during Dunkirk, the exposed film was recovered, and the salt-watered footage still developed.',
  'The Blair Witch actors were given GPS waypoints, rationed food, and notes instead of a script; the crew shook their tent at night without warning.',
  'Paranormal Activity cost about $15,000 and grossed nearly $200m — the "security camera" framing made the audience scan the frame like a Where\'s Waldo of dread.',
  'The Godfather\'s orange motif — oranges appear before violence — was partly production designer Dean Tavoularis brightening drab sets, later embraced as omen.',
  'Se7en\'s studio demanded the box ending be cut; Fincher, Pitt and Freeman jointly refused. Pitt\'s contract reportedly required the head stay in the box.',
  'Fincher is famous for double-digit take counts on dialogue — The Social Network\'s opening scene reportedly ran 99 takes of nine script pages.',
  'Michael Mann shot Collateral\'s LA nights on early digital cameras because film couldn\'t see the sodium-lit sky glow — the milky night look was a sensor artifact he embraced.',
  'Heat\'s downtown gunfight used blanks with full theatrical charge inside real streets; Mann had actors trained by ex-SAS soldiers until reloads were reflexive.',
  'The Terminator\'s future-war scenes were shot at night partly to hide low-budget miniatures — a constraint that defined the franchise\'s look.',
  'Back to the Future shot for five weeks with Eric Stoltz as Marty before recasting Michael J. Fox and reshooting — Fox filmed sitcom days and movie nights.',
  'E.T.\'s face was modelled partly on Einstein, Carl Sandburg and a pug; the puppet had controllers for 150 separate movements.',
  'The Exorcist\'s bedroom set was refrigerated to make breath visible — cast and crew worked in coats between takes in sub-zero air.',
  'Singin\' in the Rain\'s title number was shot over days with Gene Kelly reportedly running a fever; the rain had to be backlit to register on film at all.',
  'Buster Keaton\'s falling house facade in Steamboat Bill, Jr. had two inches of clearance around his body. The crew reportedly couldn\'t watch.',
  'Harold Lloyd did his clock-face climb in Safety Last! missing a thumb and forefinger from an earlier prop-bomb accident, hidden by a prosthetic glove.',
  'Keaton\'s cameras undercranked chase scenes to ~16fps so projection at speed made stunts crisper — silent comedy timing is partly a frame-rate trick.',
  'Chaplin shot 342 takes of the flower-girl meeting in City Lights over months, at one point firing and rehiring his lead actress, hunting one gesture.',
  'Casablanca\'s fog-bound plane was a half-size cutout; the mechanics around it were played by little people to sell the forced perspective.',
  'Gone with the Wind\'s burning of Atlanta torched old sets — including the great wall from King Kong — before principal photography even began.',
  'Metropolis used the "Schüfftan process": mirrors angled in front of the lens combined actors with miniature cityscapes in a single in-camera exposure.',
  'Abel Gance\'s Napoléon (1927) ended in Polyvision — three synchronized projectors forming a triptych — decades before Cinerama tried the same idea.',
  'CinemaScope\'s anamorphic trick — squeezing a wide image onto normal film with cylindrical lenses — was adapted from a WWI tank-periscope optic by Henri Chrétien.',
  'Anamorphic lenses are why cinematic bokeh is oval and lens flares streak horizontally — artifacts of the cylindrical squeeze that became a "film look" shorthand.',
  'VistaVision ran 35mm film sideways for a bigger negative in 1954; it faded within years, then returned as the effects format for Star Wars and Indiana Jones.',
  '"Day for night" shoots night scenes in daylight — underexpose, filter blue, avoid the sky. French crews called it "la nuit américaine": the American night.',
  'The "poor man\'s process" fakes driving scenes on a stage with moving lights and crew rocking the car — still used constantly because real car rigs eat shooting days.',
  'Rear-projection driving plates persisted for decades because early sound cameras were sealed in booths — the actors could stay near hidden microphones.',
  'Early talkies hid microphones in flower vases and costumes; cameras were locked in soundproof booths, which is why 1929 films suddenly stopped moving.',
  'Max Ophüls put cameras on cranes, dollies and even swings for continuous flowing takes in the 1950s — Kubrick named him a favourite and quoted his moves.',
  'Robert Altman miked every actor separately and let dialogue overlap, mixing in post — Nashville\'s soundtrack is closer to a live music desk than a movie mix.',
  'Terrence Malick\'s crews keep shooting through "dead" moments — birds landing, light shifting — because his edits are built from accidents, not coverage.',
  'Wes Anderson\'s Grand Budapest Hotel exteriors are a 3-metre miniature; he considers the slight model-ness a feature, like illustrations in a storybook.',
  'Stop-motion king Ray Harryhausen animated Jason and the Argonauts\' skeleton fight at roughly 13 seconds of screen time per week of work.',
  'King Kong (1933) mixed stop-motion Kong with full-size hand and head rigs; Kong\'s fur ripples because animators\' fingers pressed it between frames — a "flaw" audiences read as breathing.',
  'Godzilla\'s original suit weighed about 100kg; actor Haruo Nakajima fainted repeatedly inside it under tungsten studio lights.',
  'Jurassic Park\'s CGI dinosaurs got roughly six minutes of screen time; the rest is animatronics and puppetry — restraint that\'s why it still holds up.',
  'Toy Story\'s frames took from 45 minutes to 30 hours each to render in 1995 — the farm was 117 machines running around the clock.',
  'The Lord of the Rings crowd software "Massive" gave each digital soldier a tiny brain; early tests famously had some agents flee the battlefield.',
  'Se7en and Fight Club pioneered mainstream "bleach bypass" looks — skipping a chemical bath to leave silver in the print, crushing blacks and desaturating skin.',
  'The Coens shot Fargo\'s snowbound exteriors during one of Minnesota\'s mildest winters on record — crews chased snow across two states, hauling it in when they lost.',
  'Doctor Zhivago\'s Russian winter was largely shot in Spain in summer — marble dust and plastic sheeting for snow, cast in furs at 30°C.',
  'Apocalypse Now\'s sets were destroyed by Typhoon Olga, Martin Sheen had a heart attack mid-shoot, and the schedule went from 5 months to over a year — all documented in Hearts of Darkness.',
  'Storaro lit Apocalypse Now\'s Kurtz compound to swallow Brando in darkness partly because Brando arrived heavier than expected and unprepared — the shadows are a performance workaround.',
  'On Taxi Driver, "You talkin\' to me?" isn\'t in the script — the page just says Travis speaks to himself in the mirror. De Niro improvised into the gap.',
  'Jack Nicholson\'s Cuckoo\'s Nest group-therapy scenes were shot with cameras hidden from the actors\' eyelines so no one knew when they were on camera — reactions stayed live.',
  'Dog Day Afternoon\'s "Attica!" chant was suggested to Pacino by the AD moments before the take; the extras\' roar was their genuine first reaction.',
  'The Silence of the Lambs shoots Lecter looking almost straight into the lens; Demme\'s close-ups put the audience in Clarice\'s exact eyeline — the technique is why he feels inescapable.',
  'Roger Deakins didn\'t win an Oscar until his 14th nomination (Blade Runner 2049) — after decades of Shawshank, Fargo and No Country losses.',
  'Lubezki won three cinematography Oscars in a row — Gravity, Birdman, The Revenant — a first in the category\'s history.',
  'Birdman\'s "single take" is roughly a hundred hidden stitches; some seams pass through whip pans and dark doorways, others are digital morphs several seconds long.',
  'Hitchcock planned Psycho\'s shower scene with 78 setups for 45 seconds of film — and reportedly had the storyboards followed so closely he claimed the film was already made on paper.',
];
