// @ts-check
import js from '@eslint/js';
import tsPlugin from '@typescript-eslint/eslint-plugin';
import tsParser from '@typescript-eslint/parser';
import nextPlugin from '@next/eslint-plugin-next';
import reactHooks from 'eslint-plugin-react-hooks';

/**
 * Flat config, run directly via `eslint .` — not through `next lint`, which
 * feeds this file legacy eslintrc options and dies with "Unknown options:
 * useEslintrc, extensions, …". `next lint` is also deprecated in Next 15.
 */

/** @type {import('eslint').Linter.FlatConfig[]} */
const config = [
  js.configs.recommended,
  {
    files: ['**/*.ts', '**/*.tsx'],
    plugins: {
      '@typescript-eslint': tsPlugin,
      '@next/next': nextPlugin,
      'react-hooks': reactHooks,
    },
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        ecmaVersion: 2022,
        sourceType: 'module',
      },
    },
    rules: {
      ...tsPlugin.configs.recommended.rules,
      ...nextPlugin.configs.recommended.rules,
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
      // Stale-closure detection. Warn, not error: the existing disable comments
      // are deliberate, and a hook-dep nit shouldn't block a commit.
      'react-hooks/exhaustive-deps': 'warn',
      // `while (true)` is the worker-pool idiom used in the generation routes.
      'no-constant-condition': ['error', { checkLoops: false }],
      'no-console': 'off',
      'no-undef': 'off', // TypeScript handles this
    },
  },
  {
    // next-env.d.ts is generated by Next on every build — its triple-slash
    // references are not ours to fix.
    ignores: ['.next/**', 'node_modules/**', 'dist/**', 'next-env.d.ts'],
  },
];

export default config;
